### ISSUE TITLE
'experimental/filesystem' file not found

### ISSUE THREAD

**Issue by fcollot** [medInria/medInria-public#423]
(This issue was discussed in https://github.com/medInria/medInria-public/pull/392)

The current master does not compile on macos versions prior to 10.14.6.

'''
/Users/florent.collot/Work/medInria3/medInria-public/src/app/medInria/medLogger.cpp:7:12: fatal error: 'experimental/filesystem' file not found
'''

Is there an easy fix for this (which doesn't require upgrading, as that is not currently an option in MUSIC because of constraints on the clinical side) ?

**Comment by mathildemerle** [comment]
(Perhaps the easy fix would be to put back the "music" old code for that part for compilation without filesystem or experimental/filesystem. @Florent2305 is on it as far as i know)

**Comment by fcollot** [comment]
Yes I was going to do that on our fork after seeing it wasn't a big change.

**Comment by fcollot** [comment]
(but the fix I was asking about was for this repo)
